backend:
  name: git-gateway
  branch: business

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/landing/index.md"
        label: "Landing Page"
        name: "landing"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Internal", name: "internal", widget: "hidden" }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: markdown },
                  { label: Subtitle, name: subtitle, widget: text },
                  { label: Action, name: action, widget: text },
                ],
            }
          - {
              label: Bio,
              name: bio,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: markdown },
                  {
                    label: Features,
                    name: features,
                    widget: list,
                    fields:
                      [
                        { label: Header, name: header, widget: text },
                        { label: Body, name: body, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body, name: body, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Action, name: action, widget: string },
                  { label: Link, name: link, widget: string },
                  {
                    label: Tags,
                    name: tags,
                    widget: list,
                    field:
                      { label: Tagelement, name: tagelement, widget: string },
                  },
                ],
            }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Action, name: action, widget: string },
                ],
            }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Internal", name: "internal", widget: "hidden" }
